# Generated by Django 3.2.19 on 2023-07-03 11:59

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("paid_until", models.DateField(blank=True, null=True)),
                (
                    "on_trial",
                    models.BooleanField(
                        help_text="Make this false will create charge-over subscription."
                    ),
                ),
                ("trial_expiration_date", models.DateField(blank=True, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "owner_first_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "owner_last_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("owner_email", models.EmailField(max_length=254)),
                ("owner_password", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="customer.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
